name: nautilus_wallet_flutter
description: Nautilus - Fast, Robust & Secure NANO Wallet.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
version: 0.4.0+42

environment:
  sdk: '>=2.12.0 < 3.0.0'
  # sdk: ">=2.14.0 <3.0.0"
  # sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # contacts:
  flutter_contacts: ^1.1.4

  # uuid:
  uuid: ^3.0.6

  # Securley store data in a keystore
  flutter_secure_storage: ^5.0.2

  # Nano core functions
  flutter_nano_ffi: ^2.0.0

  # Shared prefs
  shared_preferences: ^2.0.8

  # animations
  lottie: ^1.3.0

  # Websockets
  web_socket_channel: ^2.0.0

  # ENS:
  ens_dart: ^1.0.0
  web3dart: ^2.3.3

  # Platform-specific build info
  package_info: ^2.0.2

  # Device-specific info
  device_info: ^2.0.3

  # JSON Serialization
  json_annotation: ^4.4.0

  # Localization
  intl: ^0.17.0

  # BigDecimal alternative
  decimal: ^2.2.0

  # Logger
  logger: ^1.0.0

  # changelog:
  package_info_plus: ^1.4.2
  flutter_markdown: ^0.6.10+2
  markdown: ^5.0.0

  # Native webview plugin
  # flutter_webview_plugin: ^0.4.0
  # new webview made by flutter:
  # webview_flutter: ^3.0.0
  flutter_inappwebview: ^5.4.3+7

  # SQLite
  sqflite: ^2.0.2+1

  # Android/iOS path provider
  # path_provider: ^2.0.1
  path_provider: ^2.0.11

  # TouchID/FaceID
  local_auth: ^2.1.0

  # Eventbus
  event_taxi: ^1.0.0

  # SVG
  flutter_svg: ^1.1.0

  # ask users to rate the app:
  rate_my_app: ^1.1.3

  # QR Codes
  qr_flutter: ^4.0.0 # Generator
  # barcode_scan2: ^4.2.1
  barcode_scan2:
    git:
      url: https://github.com/perishllc/barcode_scan2.git
      ref: main

  # Share files
  share_plus: ^4.0.4

  # File picker
  file_picker: ^4.6.1

  # Deep link support
  flutter_branch_sdk: ^5.0.0
  uni_links: ^0.5.1

  # HTTP client
  http: ^0.13.4

  # Vibrate
  flutter_vibrate: ^1.3.0

  # Toast
  # oktoast: ^3.0.0
  oktoast: ^3.2.0

  # Push notifications
  firebase_messaging: ^11.4.4
  # firebase_messaging: 11.2.8
  # firebase_core: ^1.10.0# for sure works
  # firebase_core: ^1.13.1
  firebase_core: ^1.17.1
  firebase_analytics: ^9.1.9


  # windows plugins / ffi:
  # firebase_auth: ^3.1.5
  # firebase_auth_desktop: ^0.1.1-dev.0
  # firebase_core_desktop: ^0.1.1-dev.0
  sqflite_common_ffi: ^2.1.1

  # Slidable list actions
  flutter_slidable: ^1.3.0

  # Lock helper
  synchronized: ^3.0.0

  # Service provider
  get_it: ^7.2.0

  # root / jailbreak detection
  flutter_jailbreak_detection: ^1.8.0

  # Validation utilities
  validators: ^3.0.0

  # Auto resize text widget
  auto_size_text: ^3.0.0

  # loading bar percent:
  percent_indicator: ^4.2.2

  # Avoid keyboard from overlapping text fields
  # keyboard_avoider: ^0.1.2
  keyboard_avoider:
    git:
      url: https://github.com/perishllc/keyboard_avoider
      ref: main

  # Launch external URLs
  url_launcher: ^6.0.2

  # async / general programming utilities
  quiver: ^3.1.0
  
  # devicelocale: ^0.5.1
  # 0.5.2+ requires sdk 33 and a wierd java1.8 error on android:
  devicelocale: 0.5.1

  # encryption helper:
  # flutter_sodium: ^0.2.0
  flutter_sodium:
    git:
      url: https://github.com/perishllc/flutter_sodium
      ref: main
  x25519: ^0.1.1
  encrypt: ^5.0.1

  # search bar + text highlighting:
  searchbar_animation: ^0.0.2
  substring_highlight: ^1.0.33

# dependency_overrides:
  # analyzer: ^4.1.0
  # dart_style: ^2.2.3
  # flutter_launcher_icons:
  #   git:
  #     url: https://github.com/knyghtryda/flutter_launcher_icons
  #     ref: scaling

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: ^2.1.11
  json_serializable: ^6.0.1

  intl_generator: ^0.3.0
  analyzer: ^4.1.0
  dart_style: ^2.2.3

  # screenshot generation:
  path: ^1.8.1
  file: ^6.1.2
  
  # the next two/three packages have a dependency conflict and can't both be enabled at the same time
  # though the second is just a command line tool for updating /changing the application icons
  # intl_translation:
  #   git:
  #     url: https://github.com/bbedward/intl_translation.git
  #     ref: master
  # intl_translation: ^0.17.10+1
  # flutter_native_splash: ^2.1.1
  # flutter_launcher_icons: "^0.9.2"
  # flutter_launcher_icons:
  #   git:
  #       url: https://github.com/knyghtryda/flutter_launcher_icons
  #       ref: scaling

# to update the app icons use:
# flutter pub get
# flutter pub run flutter_launcher_icons:main

# to update the translations use:
# flutter pub pub run intl_translation:extract_to_arb --output-dir=lib/l10n lib/localization.dart
# flutter pub pub run intl_translation:generate_from_arb --output-dir=lib/l10n --no-use-deferred-loading lib/localization.dart lib/l10n/intl_*.arb

flutter_icons:
  android: true
  # ios: true
  # android: "ic_launcher_round"
  # image_path: "assets/logo-square.png"
  # remove_alpha_ios: true

  image_path_android: "assets/logo-square.png"
  image_path_ios: "assets/logo-square.png"
  # icon_adaptive_foreground: "assets/foreground.png"
  # icon_adaptive_background: "assets/background.png"


  # fuscia:
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo-square.png"
  adaptive_icon_foreground_scale_factor: 0.75
  adaptive_icon_foreground_scale_fill_color: "#ffffff"
  # adaptive_icon_background: "#000000"
  # adaptive_icon_foreground: "assets/logo-square.png"
  # adaptive_icon_background: "#965353"
  # adaptive_icon_foreground: "#579653"
  # adaptive_icon_foreground_scale_factor: "sdgasdfg"

flutter_native_splash:
  # color: "#42a5f5"
  color: "#000000"
  # background_image: "assets/splash_image.png"
  branding: "assets/logo-square.png"
  android_12:
    # color: "#42a5f5"
    image: "assets/android12splash.png"
    icon_background_color: "#000000"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
          weight: 600
        - asset: fonts/NunitoSans-ExtraLight.ttf
          weight: 100
        - asset: fonts/NunitoSans-Light.ttf
          weight: 200
        - asset: fonts/NunitoSans-SemiBold.ttf
          weight: 700
        - asset: fonts/NunitoSans-Bold.ttf
          weight: 800
        - asset: fonts/NunitoSans-ExtraBold.ttf
          weight: 900
    - family: OverpassMono
      fonts:
        - asset: fonts/OverpassMono-Regular.ttf
          weight: 600
        - asset: fonts/OverpassMono-Light.ttf
          weight: 100
    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
          weight: 500
    - family: ExtraAppIcons
      fonts:
        - asset: fonts/ExtraAppIcons.ttf
          weight: 500
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: fonts/Comfortaa-Light.ttf
          weight: 300
  assets:
    - legacy_assets/QR.svg
    - legacy_assets/welcome_animation.flr
    - legacy_assets/send_animation.flr
    - legacy_assets/manta_animation.flr
    - legacy_assets/transfer_animation_nautiluswalletonly.flr
    - legacy_assets/transfer_animation_paperwalletonly.flr
    - legacy_assets/searchseedqr_animation_magnifyingglassonly.flr
    - legacy_assets/searchseedqr_animation_glassonly.flr
    - legacy_assets/searchseedqr_animation_qronly.flr
    - legacy_assets/searchseedmanual_animation_magnifyingglassonly.flr
    - legacy_assets/searchseedmanual_animation_glassonly.flr
    - legacy_assets/searchseedmanual_animation_seedonly.flr
    - legacy_assets/threedot_animation.flr
    - legacy_assets/offline_animation.flr
    - legacy_assets/sharecard_logo.svg
    - legacy_assets/transferfunds_illustration_start_nautiluswalletonly.svg
    - legacy_assets/transferfunds_illustration_start_paperwalletonly.svg
    - legacy_assets/transferfunds_illustration_end_nautiluswalletonly.svg
    - legacy_assets/transferfunds_illustration_end_paperwalletonly.svg
    - legacy_assets/pulltosend_animation.flr
    - legacy_assets/sheethandle_animation.flr
    - legacy_assets/ntr_placeholder_animation.flr
    # animations:
    - assets/animations/load-n.json
    - assets/animations/rocket.json
    - assets/animations/searching.json
    - assets/animations/loading/generic_spinner_1.json
    - assets/animations/loading/generic_spinner_2.json
    - assets/animations/loading/tri_circle_spinner.json
    - assets/animations/world-lines.json
    - assets/animations/world-plane.json
    # other assets
    - assets/store/known.json
    - assets/store/reps.json
    - assets/logo-square.png
    # nyano assets:
    - assets/nyano/images/logos/cat-head-collar-black-1000 × 1180.png
    # changelog:
    - CHANGELOG.md

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
