name: nautilus_wallet_flutter
description: Nautilus - Fast, Robust & Secure NANO Wallet.

publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
version: 0.6.6+94

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # contacts:
  flutter_contacts: ^1.1.4

  # uuid:
  uuid: ^3.0.6

  # Secureley store data in a keystore
  flutter_secure_storage: ^6.0.0

  # Nano core functions
  # flutter_nano_ffi: ^2.0.0
  flutter_nano_ffi:
    git:
      url: https://github.com/appditto/flutter_nano_ffi.git
      ref: master

  # Shared prefs
  shared_preferences: ^2.0.8

  # animations
  lottie: ^1.3.0

  # intro page:
  animated_text_kit: ^4.2.2

  # Websockets
  web_socket_channel: ^2.0.0

  # ENS:
  ens_dart: ^1.0.0

  # Platform-specific build info
  package_info: ^2.0.2

  # Device-specific info
  device_info_plus: ^4.1.2
  android_id: ^0.0.7

  # JSON Serialization
  json_annotation: ^4.6.0

  # Localization
  intl: ^0.17.0
  # BigDecimal alternative
  decimal: ^2.2.0

  # Logger
  logger: ^1.0.0

  # changelog:
  package_info_plus: ^1.4.2
  flutter_markdown: ^0.6.10+2
  # markdown: ^6.0.0

  # Native webview plugin
  # flutter_webview_plugin: ^0.4.0
  # new webview made by flutter:
  # webview_flutter: ^3.0.0
  flutter_inappwebview: ^5.4.3+7

  # SQLite
  # sqflite: ^2.0.2+1
  sqflite: ^2.1.0

  # Android/iOS path provider
  # path_provider: ^2.0.1
  path_provider: ^2.0.11

  # TouchID/FaceID
  local_auth: ^2.1.0

  # Eventbus
  event_taxi: ^1.0.0

  # SVG
  flutter_svg: ^1.1.3

  # nfc:
  nfc_manager: ^3.2.0
  # flutter_nfc_kit: ^3.3.1
  # ndef: ^0.3.1
  # flutter_nearby_connections: ^1.1.1
  # nearby messages (google / crossplatform API):
  # flutter_nearby_messages_api: ^0.0.8
  # reliably check connection status:
  internet_connection_checker: ^0.0.1+4
  connectivity_plus: ^2.3.6

  # ask users to rate the app:
  rate_my_app: ^1.1.3

  # QR Codes
  qr_flutter: ^4.0.0 # Generator
  pretty_qr_code: ^2.0.2
  # barcode_scan2: ^4.2.1
  barcode_scan2:
    git:
      url: https://github.com/perishllc/barcode_scan2.git
      ref: main

  # Share files
  share_plus: ^4.3.0

  # File picker
  file_picker: ^5.2.0

  # Deep link support
  flutter_branch_sdk: ^6.0.0
  # uni_links: ^0.5.1
  # uni_links2: ^0.6.0+1
  uni_links:
    git:
      url: https://github.com/perishllc/uni_links.git
      path: uni_links
      ref: main

  # HTTP client
  http: ^0.13.4

  # Vibrate
  flutter_vibrate: ^1.3.0

  # Toast
  # oktoast: ^3.0.0
  oktoast: ^3.2.0

  # Push notifications
  firebase_messaging: ^13.0.0
  # firebase_messaging: 11.2.8
  # firebase_core: ^1.10.0# for sure works
  # firebase_core: ^1.13.1
  firebase_core: ^1.21.1
  firebase_analytics: ^9.1.9
  firebase_app_check: ^0.0.7

  # windows plugins / ffi:
  # firebase_auth: ^3.1.5
  # firebase_auth_desktop: ^0.1.1-dev.0
  # firebase_core_desktop: ^0.1.1-dev.0
  sqflite_common_ffi: ^2.1.1

  # Slidable list actions
  flutter_slidable: ^2.0.0

  # Lock helper
  synchronized: ^3.0.0

  # Service provider
  get_it: ^7.2.0

  # root / jailbreak detection
  flutter_jailbreak_detection: ^1.8.0

  # Validation utilities
  validators: ^3.0.0

  # Auto resize text widget
  auto_size_text: ^3.0.0

  # loading bar percent:
  percent_indicator: ^4.2.2

  # Avoid keyboard from overlapping text fields
  # keyboard_avoider: ^0.1.2
  keyboard_avoider:
    git:
      url: https://github.com/perishllc/keyboard_avoider
      ref: main

  # Launch external URLs
  url_launcher: ^6.0.2

  # async / general programming utilities
  quiver: ^3.1.0

  devicelocale: ^0.5.5


  # encryption helper:
  # flutter_sodium: ^0.2.0
  flutter_sodium:
    git:
      url: https://github.com/perishllc/flutter_sodium
      ref: main
  x25519: ^0.1.1
  encrypt: ^5.0.1

  # xmr:
  # flutter_libmonero:
  #   git:
  #     url: https://github.com/cypherstack/flutter_libmonero.git
  #     ref: a63b69fd4cc437b789f82085c3cdb50b3b99db94
  # cw_core:
  #   git:
  #     url: https://github.com/cypherstack/flutter_libmonero.git
  #     ref: a63b69fd4cc437b789f82085c3cdb50b3b99db94
  #     path: cw_core
  # cw_monero:
  #   git:
  #     url: https://github.com/cypherstack/flutter_libmonero.git
  #     ref: a63b69fd4cc437b789f82085c3cdb50b3b99db94
  #     path: cw_monero
  # cw_shared_external:
  #   git:
  #     url: https://github.com/cypherstack/flutter_libmonero.git
  #     ref: a63b69fd4cc437b789f82085c3cdb50b3b99db94
  #     path: cw_shared_external
  # cw_core:
  #   path: ./crypto_plugins/flutter_libmonero/cw_core
  # cw_monero:
  #   path: ./crypto_plugins/flutter_libmonero/cw_monero
  # cw_shared_external:
  #   path: ./crypto_plugins/flutter_libmonero/cw_shared_external
  # flutter_libmonero:
  #   path: ./crypto_plugins/flutter_libmonero

  # search bar + text highlighting:
  searchbar_animation: ^0.0.2
  substring_highlight: ^1.0.33

  # localization:
  intl_utils: ^2.7.0

  # confetti:
  confetti: ^0.7.0

  
  path: ^1.8.1

  # hcaptcha:
  webview_flutter: ^3.0.4
  app_tracking_transparency: ^2.0.2+4


  # quick_usb: ^0.4.0

flutter_intl:
  enabled: true
  class_name: AppLocalization
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false
  upload_overwrite: true
  localizely:
    project_id: 6991a0b2-4aa6-49c1-82d8-fcd38488d8b4

dependency_overrides:
  ffi: ^2.0.1
  web3dart: 2.0.0
  # analyzer: ^4.1.0
  # dart_style: ^2.2.3
  # flutter_launcher_icons:
  #   git:
  #     url: https://github.com/knyghtryda/flutter_launcher_icons
  #     ref: scaling
  uni_links_platform_interface:
    git:
      url: https://github.com/perishllc/uni_links.git
      path: uni_links_platform_interface
      ref: main

  # https://github.com/pichillilorenzo/flutter_inappwebview/issues/1223
  flutter_inappwebview:
    git:
      url: https://github.com/rshrc/flutter_inappwebview
      ref: master
  # device_info_plus_platform_interface: 2.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: ^2.1.11
  json_serializable: ^6.3.1
  analyzer: ^4.7.0
  dart_style: ^2.2.3

  # screenshot generation:
  file: ^6.1.2

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
          weight: 600
        - asset: fonts/NunitoSans-ExtraLight.ttf
          weight: 100
        - asset: fonts/NunitoSans-Light.ttf
          weight: 200
        - asset: fonts/NunitoSans-SemiBold.ttf
          weight: 700
        - asset: fonts/NunitoSans-Bold.ttf
          weight: 800
        - asset: fonts/NunitoSans-ExtraBold.ttf
          weight: 900
    - family: OverpassMono
      fonts:
        - asset: fonts/OverpassMono-Regular.ttf
          weight: 600
        - asset: fonts/OverpassMono-Light.ttf
          weight: 100
    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
          weight: 500
    - family: ExtraAppIcons
      fonts:
        - asset: fonts/ExtraAppIcons.ttf
          weight: 500
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: fonts/Comfortaa-Light.ttf
          weight: 300
  assets:
    # animations:
    - assets/animations/load-n.json
    - assets/animations/rocket.json
    - assets/animations/searching.json
    - assets/animations/loading/generic_spinner_1.json
    - assets/animations/loading/generic_spinner_2.json
    - assets/animations/loading/tri_circle_spinner.json
    - assets/animations/world-lines.json
    - assets/animations/world-plane.json
    # other assets
    # - assets/store/known.json
    # - assets/store/reps.json
    # - assets/logo-square.png
    - assets/logo.png
    - assets/logos/nanocafe.png
    - assets/logos/redeemforme.png
    - assets/logos/onramper.png
    - assets/logos/nanswap.png
    # - assets/logos/redeemforme.svg
    # nyano assets:
    - assets/nyano/images/logos/cat-head-collar-black-1000 × 1180.png
    # illustrations:
    - assets/illustrations/transferfunds_start.svg
    - assets/illustrations/transferfunds_paperwalletonly.svg
    # changelog:
    - CHANGELOG.md
    # xmr:
    - assets/xmr/
    - assets/xmr/index.html
    - assets/xmr/main.js
    - assets/xmr/monero_wallet_full.js
    - assets/xmr/monero_wallet_full.wasm
    - assets/xmr/monero_web_worker.js

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
